# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'VoximplantDemo' do
    # Pods for VoximplantDemo
    pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge',
    'RCTImage',
    'RCTNetwork',
    'RCTText',
    'RCTWebSocket',
    'DevSupport',
    'RCTAnimation',
    'RCTLinkingIOS'
    # Add any other subspecs you want to use in your project
    ]

    # Demo project dependencies
    pod 'react-native-voximplant', path: '../node_modules/react-native-voximplant'
    pod 'RNCAsyncStorage', path: '../node_modules/@react-native-community/async-storage/'
    pod 'react-native-notifications', path: '../node_modules/react-native-notifications'
    pod 'RNCallKit', path: '../node_modules/react-native-callkit'

    # Explicitly include Yoga if you are using RN >= 0.42.0
    pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

    # Third party deps podspec link
    pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
    pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/GLog.podspec'
    pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
    
    post_install do |installer|
        installer.pods_project.targets.each do |target|
            target.build_configurations.each do |config|
                config.build_settings['ENABLE_BITCODE'] = 'NO'
            end
        end
    end
    
    target 'VoximplantDemoTests' do
    	inherit! :search_paths
    end
    
end

