# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'VoximplantDemo' do
    # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
     use_frameworks!
    
    # Pods for VoximplantDemo
    pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge',
    'RCTImage',
    'RCTNetwork',
    'RCTText',
    'RCTWebSocket',
    'DevSupport',
    'RCTAnimation',
    'RCTLinkingIOS'
    # Add any other subspecs you want to use in your project
    ]

    # Demo project dependencies
    pod 'react-native-voximplant', path: '../node_modules/react-native-voximplant'
    pod 'react-native-notifications', path: '../node_modules/react-native-notifications'
    pod 'RNCallKit', path: '../node_modules/react-native-callkit'

    # Explicitly include Yoga if you are using RN >= 0.42.0
    pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

    # Third party deps podspec link
    pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
    pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/GLog.podspec'
    pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
    
    post_install do |installer|
        installer.pods_project.targets.each do |target|
            if target.name == 'React'
                target.build_configurations.each do |config|
                    xcconfig_path = config.base_configuration_reference.real_path
                    xcconfig = File.read(xcconfig_path)
                    new_xcconfig = xcconfig.sub('HEADER_SEARCH_PATHS = $(inherited)', 'HEADER_SEARCH_PATHS = $(inherited) "$(PODS_TARGET_SRCROOT)/ReactCommon/jsiexecutor"')
                    File.open(xcconfig_path, "w") { |file| file << new_xcconfig }
                end
            end
            target.build_configurations.each do |config|
                config.build_settings['ENABLE_BITCODE'] = 'NO'
            end
        end
    end
    
    target 'VoximplantDemoTests' do
    	inherit! :search_paths
    end
    
end

