# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VoxImplantDemo' do
    # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
     use_frameworks!
    
    # Pods for VoximplantDemo
    pod 'React', :path => ‘../node_modules/react-native', :subspecs => [
    'Core',
    'RCTImage',
    'RCTNetwork',
    'RCTText',
    'RCTWebSocket',
    'DevSupport',
    'BatchedBridge',
    'RCTAnimation'
    # Add any other subspecs you want to use in your project
    ]
    pod 'react-native-voximplant', path: '../node_modules/react-native-voximplant'
    pod 'Yoga', path: '../node_modules/react-native/ReactCommon/yoga'
    pod 'RNDefaultPreference', path: '../node_modules/react-native-default-preference'
    pod 'react-native-notifications', path: '../node_modules/react-native-notifications'
    
    inherit! :search_paths
    
    post_install do |installer|
        installer.pods_project.targets.each do |target|
            target.build_configurations.each do |config|
                config.build_settings['ENABLE_BITCODE'] = 'NO'
            end
        end
    end
    
    
end

target 'VoxImplantDemoTests' do
    # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
     use_frameworks!
    
    # Pods for VoximplantDemo
    pod 'React', :path => ‘../node_modules/react-native', :subspecs => [
    'Core',
    'RCTImage',
    'RCTNetwork',
    'RCTText',
    'RCTWebSocket',
    'DevSupport',
    'BatchedBridge',
    'RCTAnimation'
    # Add any other subspecs you want to use in your project
    ]
    pod 'react-native-voximplant', path: '../node_modules/react-native-voximplant'
    pod 'Yoga', path: '../node_modules/react-native/ReactCommon/yoga'
    pod 'RNDefaultPreference', path: '../node_modules/react-native-default-preference'
    pod 'react-native-notifications', path: '../node_modules/react-native-notifications'
    
    inherit! :search_paths
end

