/*
 * Copyright (c) 2011-2022, Zingaya, Inc. All rights reserved.
 */

export const conferenceActions = {
  TOGGLE_IS_MUTED: 'TOGGLE_IS_MUTED',
  TOGGLE_LOCAL_VIDEO: 'TOGGLE_LOCAL_VIDEO',
  CHANGE_CALL_STATE: 'CHANGE_CALL_STATE',
  CALL_FAILED: 'CALL_FAILED',
  ADD_PARTICIPANT: 'ADD_PARTICIPANT',
  LOCAL_VIDEO_STREAM_ADDED: 'LOCAL_VIDEO_STREAM_ADDED',
  LOCAL_VIDEO_STREAM_REMOVED: 'LOCAL_VIDEO_STREAM_REMOVED',
  REMOVE_PARTICIPANT: 'REMOVE_PARTICIPANT',
  ENDPOINT_ADDED: 'ENDPOINT_ADDED',
  REMOTE_VIDEO_STREAM_ADDED: 'REMOTE_VIDEO_STREAM_ADDED',
  REMOTE_VIDEO_STREAM_REMOVED: 'REMOTE_VIDEO_STREAM_REMOVED',
  ENDPOINT_REMOVED: 'ENDPOINT_REMOVED',
};