/*
 * Copyright (c) 2011-2022, Zingaya, Inc. All rights reserved.
 */

export const conferenceActions = {
  TOGGLE_MUTE: 'TOGGLE_MUTE',
  TOGGLE_SEND_VIDEO: 'TOGGLE_SEND_VIDEO',
  CHANGE_CALL_STATE: 'CHANGE_CALL_STATE',
  CALL_FAILED: 'CALL_FAILED',
  VIDEO_STREAM_ADDED: 'VIDEO_STREAM_ADDED',
  VIDEO_STREAM_REMOVED: 'VIDEO_STREAM_REMOVED',
  ENDPOINT_ADDED: 'ENDPOINT_ADDED',
  ENDPOINT_REMOVED: 'ENDPOINT_REMOVED',
  SET_ERROR: 'SET_ERROR',
  REMOVE_ALL_PARTICIPANTS: 'REMOVE_ALL_PARTICIPANTS',
  ENDPOINT_VOICE_ACTIVITY_STARTED: 'ENDPOINT_VOICE_ACTIVITY_STARTED',
  ENDPOINT_VOICE_ACTIVITY_STOPPED: 'ENDPOINT_VOICE_ACTIVITY_STOPPED',
  ENDPOINT_MUTED: 'ENDPOINT_MUTED',
  SET_SELECTED_AUDIO_DEVICE: 'SET_SELECTED_AUDIO_DEVICE',
  SET_LIST_AUDIO_DEVICES: 'SET_LIST_AUDIO_DEVICES',
};