/*
 * Copyright (c) 2011-2022, Zingaya, Inc. All rights reserved.
 */

export const conferenceActions = {
  TOGGLE_IS_MUTED: 'TOGGLE_IS_MUTED',
  TOGGLE_LOCAL_VIDEO: 'TOGGLE_LOCAL_VIDEO',
  CHANGE_CALL_STATE: 'CHANGE_CALL_STATE',
  CALL_FAILED: 'CALL_FAILED',
  UPDATE_PARTICIPANTS: 'UPDATE_PARTICIPANTS',
  REMOVE_PARTICIPANT: 'REMOVE_PARTICIPANT',
};